version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask_app
  flask_app:
    container_name: flask_app
    volumes:
      - books:/bot/books
    build: .
    command: gunicorn -b 0.0.0.0:8000 -w 1 "wsgi:app"
    restart: always
    ports:
      - 8000:8000
    networks:
      my-network:
    environment:
      - ADMIN_TG_ID=
      - DATABASE_HOST=
      - DATABASE_PASSWORD=
      - DATABASE_PORT=
      - TG_TOKEN=
      - URL=
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email andimeon@gmail.com --agree-tos --no-eff-email --staging -d bookbot.andimeon.com

volumes:
  books: {}
  certbot-etc:
  certbot-var:
networks:
  my-network:
