version: "3"
services:
  book-bot:
    volumes:
      - .:/bot/books
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - ADMIN_TG_ID=
      - DATABASE_HOST=
      - DATABASE_PASSWORD=
      - DATABASE_PORT=
      - TG_TOKEN=
      - URL=

volumes:
  logvolume01: {}
